config-version: 3

player-token: '%p'

x-token: '%x'

y-token: '%y'

y-air-token: '%Y'

z-token: '%z'

options:
- name: default
  limit: -1
- name: group.guest
  limit: 5

powertools:
  sulphur:
    left-click: version
    right-click: plugins

verbose: true

debug: false
