name: PowerTool
version: ${version}
main: org.tyrannyofheaven.bukkit.PowerTool.PowerToolPlugin
description: Temporarily bind commands to the current in-hand item
author: ZerothAngel

commands:
  powertool:
    description: Top-level command for PowerTool
    aliases: [ptool, pt]

permissions:
  powertool.use:
    description: Allows use of the use of power tools
    default: op
  powertool.reload:
    description: Allows use of /powertool reload
    default: op
