name: PowerTool
version: ${version}
main: org.tyrannyofheaven.bukkit.PowerTool.PowerToolPlugin
description: Temporarily bind commands to the current in-hand item
author: ZerothAngel

commands:
  powertool:
    description: Top-level command for PowerTool
    aliases: [ptool, pt]

permissions:
  powertool.use:
    description: Allows full use and creation of power tools
    default: op
    children:
      powertool.use.*: true
      powertool.create: true
  powertool.use.*:
    description: Allows full use of power tools
    default: op
  powertool.create:
    description: Allows creation of power tools
    default: op
  powertool.reload:
    description: Allows use of /powertool reload
    default: op
