name: PowerTool
version: ${version}
main: org.tyrannyofheaven.bukkit.PowerTool.PowerToolPlugin
description: Temporarily bind commands to the current in-hand item
author: ZerothAngel

commands:
  powertool:
    description: Set or clear a powertool
    aliases: pt

permissions:
  powertool.use:
    description: Allows use of the /powertool command
    default: op
